

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.intellijthemes.FlatOneDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTAtomOneDarkIJTheme;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class InvoiceApplication extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceApplication
     */
    public InvoiceApplication() {
        initComponents();
    }
    int In_Num = 1;

    private void Auto_Total_Calculate() {
        DefaultTableModel dtm = (DefaultTableModel) jT_Product.getModel();
        double Total = 0;
        for (int i = 0; i < jT_Product.getRowCount(); i++) {
            String Unit_Total = dtm.getValueAt(i, 4).toString();
            double Item_Total = Double.parseDouble(Unit_Total);
            Total += Item_Total;
            lbl_Total_Price.setText(Total + "0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Customer_Name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Product = new javax.swing.JTable();
        Product_Name = new javax.swing.JLabel();
        Product_Qty = new javax.swing.JLabel();
        txt_Customer_Name = new javax.swing.JTextField();
        txt_Product_Name = new javax.swing.JTextField();
        txt_Product_Qty = new javax.swing.JTextField();
        btn_Add_to_Bill = new javax.swing.JButton();
        Total_Price = new javax.swing.JLabel();
        Discount = new javax.swing.JLabel();
        Payable_Total = new javax.swing.JLabel();
        lbl_Total_Price = new javax.swing.JLabel();
        txt_Discount = new javax.swing.JTextField();
        lbl_Payable_Total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Unit_Price = new javax.swing.JLabel();
        txt_Unit_Price = new javax.swing.JTextField();
        Whatsapp_Number = new javax.swing.JLabel();
        txt_Whatsapp_Number = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invoice App");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INVOICE");

        Customer_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Customer_Name.setText("Customer Name :");

        jT_Product.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jT_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Product Name", "Unit Price (Rs.)", "Qty", "Total (Rs.)"
            }
        ));
        jScrollPane1.setViewportView(jT_Product);

        Product_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Product_Name.setText("Product Name    :");

        Product_Qty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Product_Qty.setText("Product Qty        :");

        txt_Customer_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_Product_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_Product_Qty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_Add_to_Bill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Add_to_Bill.setText("Add to Bill");
        btn_Add_to_Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_to_BillActionPerformed(evt);
            }
        });

        Total_Price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Total_Price.setText(" Total Price (Rs.)      :");

        Discount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Discount.setText(" Discount (%)        :");

        Payable_Total.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Payable_Total.setText(" Payable Total (Rs.) :");

        lbl_Total_Price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Total_Price.setText("0.00");

        txt_Discount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_Discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DiscountKeyReleased(evt);
            }
        });

        lbl_Payable_Total.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_Payable_Total.setText("0.00");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Design By ProTech Solutions (Pvt)  Ltd");

        Unit_Price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Unit_Price.setText("Unit Price            :");

        txt_Unit_Price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Whatsapp_Number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Whatsapp_Number.setText("Whatsapp No     :");

        txt_Whatsapp_Number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Generate Invoice and send to Whatasapp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Main_PanelLayout = new javax.swing.GroupLayout(Main_Panel);
        Main_Panel.setLayout(Main_PanelLayout);
        Main_PanelLayout.setHorizontalGroup(
            Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Main_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Total_Price)
                            .addComponent(Discount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Total_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Main_PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Payable_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Payable_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))))
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addComponent(Customer_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Customer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Add_to_Bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Product_Qty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Whatsapp_Number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Product_Qty, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(txt_Whatsapp_Number))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Main_PanelLayout.createSequentialGroup()
                                .addComponent(Unit_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Unit_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Main_PanelLayout.createSequentialGroup()
                                .addComponent(Product_Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Product_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        Main_PanelLayout.setVerticalGroup(
            Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_PanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Customer_Name)
                            .addComponent(txt_Customer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Product_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Product_Name))
                        .addGap(18, 18, 18)
                        .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Unit_Price)
                            .addComponent(txt_Unit_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addComponent(btn_Add_to_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product_Qty)
                    .addComponent(txt_Product_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Whatsapp_Number)
                    .addComponent(txt_Whatsapp_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total_Price)
                    .addComponent(lbl_Total_Price)
                    .addComponent(Payable_Total))
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Discount)
                            .addComponent(txt_Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_Payable_Total)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Add_to_BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_to_BillActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jT_Product.getModel();
        if (txt_Product_Name.getText().isEmpty() && txt_Product_Qty.getText().isEmpty() && txt_Customer_Name.getText().isEmpty() && txt_Unit_Price.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Please Check Input Fields", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Vector v = new Vector();
            v.add(In_Num);
            v.add(txt_Product_Name.getText());
            v.add(txt_Unit_Price.getText());
            v.add(txt_Product_Qty.getText());
            Double Total = Double.parseDouble(txt_Unit_Price.getText()) * Double.parseDouble(txt_Product_Qty.getText());
            v.add(Total);
            
            dtm.addRow(v);
            JOptionPane.showMessageDialog(this, "Add Invoice Item Successfully", "Successfully Message", JOptionPane.INFORMATION_MESSAGE);
            Auto_Total_Calculate();
            
            txt_Product_Name.setText(null);
            txt_Product_Qty.setText(null);
            txt_Unit_Price.setText(null);
            In_Num++;
        }
    }//GEN-LAST:event_btn_Add_to_BillActionPerformed

    private void txt_DiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DiscountKeyReleased
        // TODO add your handling code here:
        double discount_Value = Double.parseDouble(txt_Discount.getText());
        double total_Value = Double.parseDouble(lbl_Total_Price.getText());
        double payable_Value = total_Value * (discount_Value / 100);
        lbl_Payable_Total.setText(total_Value - payable_Value + "0");
    }//GEN-LAST:event_txt_DiscountKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {
        // 1. Fields වලින් දත්ත ලබා ගැනීම
        String customerName = txt_Customer_Name.getText().trim();
        String whatsappNo = txt_Whatsapp_Number.getText().trim().replaceAll("[^0-9]", ""); 
        String discount = txt_Discount.getText().trim();
        String payableTotal = lbl_Payable_Total.getText().trim();
        String total=lbl_Total_Price.getText().trim();
        
        if(customerName.isEmpty()) customerName = "Customer";
        if(discount.isEmpty()) discount = "0";

        // ලංකාවේ අංකයක් නම් 94 මුලට එකතු කිරීම
        if (whatsappNo.startsWith("0")) {
            whatsappNo = "94" + whatsappNo.substring(1);
        }

        // 2. PDF එක පරිගණකයේ සුරැකෙන ස්ථානය
        String pdfPath = "C:\\Invoices\\Invoice_" + customerName + ".pdf";
        java.io.File folder = new java.io.File("C:\\Invoices");
        if (!folder.exists()) {
            folder.mkdir();
        }

        // ==================== ITEXT PDF GENERATION ====================
        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
        com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(pdfPath));
        document.open();

        document.add(new com.itextpdf.text.Paragraph("                ==============================================="));
        document.add(new com.itextpdf.text.Paragraph("                                       INVOICE                      "));
        document.add(new com.itextpdf.text.Paragraph("                ==============================================="));
        document.add(new com.itextpdf.text.Paragraph("Customer Name: " + customerName));
        document.add(new com.itextpdf.text.Paragraph("Date: " + new java.util.Date().toString()));
        document.add(new com.itextpdf.text.Paragraph(" ")); 

        com.itextpdf.text.pdf.PdfPTable pdfTable = new com.itextpdf.text.pdf.PdfPTable(5);
        pdfTable.addCell("No");
        pdfTable.addCell("Product Name");
        pdfTable.addCell("Unit Price (Rs.)");
        pdfTable.addCell("Qty");
        pdfTable.addCell("Total (Rs.)");

        for (int i = 0; i < jT_Product.getRowCount(); i++) {
            pdfTable.addCell(jT_Product.getValueAt(i, 0) != null ? String.valueOf(jT_Product.getValueAt(i, 0)) : ""); 
            pdfTable.addCell(jT_Product.getValueAt(i, 1) != null ? String.valueOf(jT_Product.getValueAt(i, 1)) : ""); 
            pdfTable.addCell(jT_Product.getValueAt(i, 2) != null ? String.valueOf(jT_Product.getValueAt(i, 2)) : ""); 
            pdfTable.addCell(jT_Product.getValueAt(i, 3) != null ? String.valueOf(jT_Product.getValueAt(i, 3)) : ""); 
            pdfTable.addCell(jT_Product.getValueAt(i, 4) != null ? String.valueOf(jT_Product.getValueAt(i, 4)) : ""); 
        }
        document.add(pdfTable); 

        document.add(new com.itextpdf.text.Paragraph(" "));
         document.add(new com.itextpdf.text.Paragraph("Total Price : " + total ));
        document.add(new com.itextpdf.text.Paragraph("Discount (%): " + discount + "%"));
        document.add(new com.itextpdf.text.Paragraph("Payable Total (Rs.): " + payableTotal));
        document.add(new com.itextpdf.text.Paragraph(" "));
        document.add(new com.itextpdf.text.Paragraph("Design By ProTech Solutions (Pvt) Ltd"));
        
        document.close(); 
        // =====================================================================


        // ==================== WHATSAPP AUTOMATION TRICK ====================
        java.io.File file = new java.io.File(pdfPath);
        java.util.List<java.io.File> listOfFiles = new java.util.ArrayList<>();
        listOfFiles.add(file);
        FileTransferable ft = new FileTransferable(listOfFiles);
        java.awt.Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ft, null);

        // 🎯 මෙන්න මේ නිල ලින්ක් එක විතරක්ම දමන්න. (මැද ://whatsapp.com ලෙස වෙනස් කර ඇත, බ්‍රවුසර් බ්ලොක් මඟහැරීමට)
        String whatsappURL = "https://wa.me/" + whatsappNo;

        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop.getDesktop().browse(new java.net.URI(whatsappURL));
        }

        // WhatsApp Web ලෝඩ් වනතුරු තත්පර 12ක් සිටීම
        Thread.sleep(12000);

        java.awt.Robot robot = new java.awt.Robot();
        
        // Ctrl + V (PDF එක Paste කිරීම)
        robot.keyPress(java.awt.event.KeyEvent.VK_CONTROL);
        robot.keyPress(java.awt.event.KeyEvent.VK_V);
        robot.keyRelease(java.awt.event.KeyEvent.VK_V);
        robot.keyRelease(java.awt.event.KeyEvent.VK_CONTROL);

        Thread.sleep(2000);

        // Enter (Send කිරීම)
        robot.keyPress(java.awt.event.KeyEvent.VK_ENTER);
        robot.keyRelease(java.awt.event.KeyEvent.VK_ENTER);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Invoice PDF Generated & Sent via WhatsApp!");

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
       
    
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) {
  
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(InvoiceApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        try {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatIntelliJLaf());
        } catch (Exception ex) {
            Logger.getLogger(InvoiceApplication.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Customer_Name;
    private javax.swing.JLabel Discount;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JLabel Payable_Total;
    private javax.swing.JLabel Product_Name;
    private javax.swing.JLabel Product_Qty;
    private javax.swing.JLabel Total_Price;
    private javax.swing.JLabel Unit_Price;
    private javax.swing.JLabel Whatsapp_Number;
    private javax.swing.JButton btn_Add_to_Bill;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jT_Product;
    private javax.swing.JLabel lbl_Payable_Total;
    private javax.swing.JLabel lbl_Total_Price;
    private javax.swing.JTextField txt_Customer_Name;
    private javax.swing.JTextField txt_Discount;
    private javax.swing.JTextField txt_Product_Name;
    private javax.swing.JTextField txt_Product_Qty;
    private javax.swing.JTextField txt_Unit_Price;
    private javax.swing.JTextField txt_Whatsapp_Number;
    // End of variables declaration//GEN-END:variables
static class FileTransferable implements java.awt.datatransfer.Transferable {
        private java.util.List<java.io.File> list;
        public FileTransferable(java.util.List<java.io.File> list) { this.list = list; }
        public java.awt.datatransfer.DataFlavor[] getTransferDataFlavors() {
            return new java.awt.datatransfer.DataFlavor[]{java.awt.datatransfer.DataFlavor.javaFileListFlavor};
        }
        public boolean isDataFlavorSupported(java.awt.datatransfer.DataFlavor flavor) {
            return java.awt.datatransfer.DataFlavor.javaFileListFlavor.equals(flavor);
        }
        public Object getTransferData(java.awt.datatransfer.DataFlavor flavor) { return list; }
    }

}

